# Generated by Django 3.2.6 on 2021-08-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complate',
            new_name='complete',
        ),
    ]
