# Generated by Django 3.2.6 on 2021-08-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_complate_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='sate',
            new_name='state',
        ),
    ]
